version: '3.4'

services:
  bot:
    build:
      context: .
      target: build
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    dns: 
      - '8.8.8.8'